<?php
/**
 * Created by PhpStorm.
 * User: michele.lafrancesca
 * Date: 08/10/2020
 * Time: 16:51
 */

namespace open20\amos\events\helpers\google_api\widgets;


use open20\amos\events\AmosEvents;
use open20\amos\events\assets\EventsAsset;
use open20\amos\events\models\Event;
use open20\amos\events\models\EventInvitation;
use yii\base\Widget;

class AddEventTicketWidget extends Widget
{
    const TYPE_LINK = 'link';
    const TYPE_BUTTON = 'button';

    public $type = 'button';
    public $event_id;
    public $invitation_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        $event = Event::findOne($this->event_id);
        $invitation = null;
        if($this->invitation_id) {
            $invitation = EventInvitation::findOne($this->invitation_id);
        }
        if($event->canUseEventPasses()) {
            if ($this->type == self::TYPE_BUTTON) {
                $assetBundle = EventsAsset::register($this->getView());
                if (isset(\Yii::$app->params['googleApi'])) {
                    $urlGoogle = \Yii::$app->params['platform']['backendUrl'] . '/events/wallet/save-to-google?id=' . $this->event_id;
                    if($invitation){
                        $urlGoogle .= "&iid=".$invitation->id."&code=".$invitation->code;
                    }
                    $buttonGoogle = \yii\helpers\Html::a(\yii\helpers\Html::img($assetBundle->baseUrl . "/img/gpay_logo.png", [
                        'style' => 'height:18px',
                        'class' => 'img-responsive'
                    ]), $urlGoogle, [
                        'class' => 'btn btn-secondary',
                        'title' => AmosEvents::t('amosevents', "Salva su google pay")
                    ]);

                }
                if (isset(\Yii::$app->params['appleApi'])) {
                    $urlApple = \Yii::$app->params['platform']['backendUrl'] . '/events/wallet/save-to-ios?id=' . $this->event_id;
                    if($invitation){
                        $urlApple .= "&iid=".$invitation->id."&code=".$invitation->code;
                    }
                    $buttonApple = \yii\helpers\Html::a(AmosEvents::t('amosevents', 'Save To Apple Wallet'), $urlApple, [
                        'class' => 'btn btn-primary'
                    ]);
                    return $buttonGoogle . $buttonApple;
                }

            } else if ($this->type == self::TYPE_LINK) {
                $buttonGoogle = '';
                if (isset(\Yii::$app->params['googleApi'])) {
                    $urlGoogle = \Yii::$app->params['platform']['backendUrl'] . '/events/wallet/save-to-google?id=' . $this->event_id;
                    if($invitation){
                        $urlGoogle .= "&iid=".$invitation->id."&code=".$invitation->code;
                    }
                    $buttonGoogle = \yii\helpers\Html::a("Salva su google Pay", $urlGoogle, [
                        'title' => AmosEvents::t('amosevents', "Salva su google pay")
                    ]);

                }
                $buttonApple ='';
                if (isset(\Yii::$app->params['appleApi'])) {
                    $urlApple = \Yii::$app->params['platform']['backendUrl'] . '/events/wallet/save-to-ios?id=' . $this->event_id;
                    if($invitation){
                        $urlApple .= "&iid=".$invitation->id."&code=".$invitation->code;
                    }
                    $buttonApple = \yii\helpers\Html::a(AmosEvents::t('amosevents', 'Salva su Apple Wallet'), $urlApple, [
                    ]);
                }
                return $buttonGoogle . " o " . $buttonApple;

            }
        }
        return '';
    }
    
    static function GetGooglePay($event_id,$invitation_id){
        $event = Event::findOne($event_id);
        $invitation = null;
        if($invitation_id) {
            $invitation = EventInvitation::findOne($invitation_id);
        }
        if (isset(\Yii::$app->params['googleApi'])) {
            $urlGoogle = \Yii::$app->params['platform']['backendUrl'] . '/events/wallet/save-to-google?id=' . $event_id;
            if($invitation){
                $urlGoogle .= "&iid=".$invitation->id."&code=".$invitation->code;
            }
        }
        return $urlGoogle;
    }
    
    static function GetApplePay($event_id,$invitation_id){
        $event = Event::findOne($event_id);
        $invitation = null;
        if($invitation_id) {
            $invitation = EventInvitation::findOne($invitation_id);
        }
        if (isset(\Yii::$app->params['appleApi'])) {
            $urlApple = \Yii::$app->params['platform']['backendUrl'] . '/events/wallet/save-to-ios?id=' . $event_id;
            if($invitation){
                $urlApple .= "&iid=".$invitation->id."&code=".$invitation->code;
            }
        }
        return $urlApple;
    }
}