<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    Open20Package
 * @category   CategoryName
 */
/**
 */

namespace open20\amos\events\models;


use open20\amos\events\AmosEvents;
use yii\base\Model;

class RegisterGroupForm extends Model
{
    public $groupName;
    public $nSeats;
    public $email;
    public $note;
    public $sector;
    public $event_id;

    /**
     * @return array
     */
    public function rules()
    {
        return[
            [['groupName','nSeats','email','sector'],'required'],
            [['groupName','nSeats','email', 'note','sector'],'safe'],
            [['nSeats'],'integer'],
            [['email'],'email'],
            [['event_id'],'integer']
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * @param string $attribute
     * @return array|string
     */
    public function getAttributeLabel($attribute)
    {
        $attributes =  [
            'groupName' => AmosEvents::txt('Nome gruppo'),
            'nSeats' => AmosEvents::txt('Numero di posti'),
            'email' => AmosEvents::txt('Email'),
            'sector' => AmosEvents::txt('Settore'),
            'note' => AmosEvents::txt('Note'),
        ]; // TODO: Change the autogenerated stub
        return $attributes[$attribute];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}